### ISSUE TITLE
Bug - Random OTRS crashing

### ISSUE THREAD

**Issue by MartinZubek** [znuny/Znuny4OTRS-GIArticleSend#11]
### Environment

- OS: Debian 11 (with MariaDB 10.5)
- Browser: Not relevant
- OTRS version:
   - Znuny LTS 6.0.45
   - Znuny4OTRS-Repo  6.0.76
   - Znuny4OTRS-GIArticleSend 6.0.8

### Expected behavior

Not to crash OTRS.

### Actual behavior

Using exactly the same REST API request, sometimes it works without a problem but other times it crashes whole OTRS instance.
Error logs and the request example is enclosed below.

### How to reproduce

1. Send this REST request:

```
POST https://{{serverUrl}}/otrs/nph-genericinterface.pl/Webservice/GenericTicketConnectorREST/Ticket
```
with body:
```json
{
	"SessionID": "{{SessionID}}",
	"Ticket": {
		"QueueID": 1,
		"TypeID": 1,
		"StateID": 4,
		"PriorityID": 3,
		"Title": "Test title",
		"CustomerUser": "recipient@address.tld"
	},
	"Article": {
		"ArticleSend": 1,
		"CommunicationChannelID": 1,
		"SenderType": "agent",
		"IsVisibleForCustomer": 1,
		"ContentType": "text/html; charset=utf-8",
		"To": "recipient@address.tld",
		"From": "sender@address.tld",
		"Subject": "Test Subject",
		"Body": "Test body"
	}
}
```
2. Most of the times the ticket is created correctly and e-mail is sent to it's recipient, but few times (appears to be random) it crashes with error:

```
[:error] [pid 2539705] Can't locate object method "Init" via package "Kernel::GenericInterface::Operation::Ticket::TicketCreate" at /opt/otrs/Custom/Kernel/GenericInterface/Operation/Ticket/TicketCreate.pm line 345.
[:error] [pid 2539692] Can't locate object method "ValidateCustomer" via package "Kernel::GenericInterface::Operation::Ticket::TicketCreate" at /opt/otrs/Custom/Kernel/GenericInterface/Operation/Ticket/TicketCreate.pm line 673.
[perl:error] [pid 2539396] [client IP:PORT] Use of each() on hash after insertion without resetting hash iterator results in undefined behavior, Perl interpreter: 0x55cbc124e080 at /opt/otrs/Kernel/cpan-lib/Apache2/Reload.pm line 171.
```

**Comment by rkaldung** [comment]
Hi @MartinZubek , Please check first which MPM-module do you use.

**Comment by MartinZubek** [comment]
Hi @rkaldung, thank you very much for your reply. We are using [prefork](https://httpd.apache.org/docs/2.4/mod/prefork.html) module.
Do you think it could be somehow related?

**Comment by rkaldung** [comment]
> Hi @rkaldung, thank you very much for your reply. We are using [prefork](https://httpd.apache.org/docs/2.4/mod/prefork.html) module.
> Do you think it could be somehow related?

No, prefork is fine. Have you restarted the web server after the installation of the module or after the last update of Perl/Perl modules?

**Comment by MartinZubek** [comment]
Huh, that's strange, it appears that another restart fixed it.
I will test it more and keep you posted if the problem reappears again, but for now it appears to be fixed.

Thank you very much for your time and help. 👍
