### ISSUE TITLE
Add support for PGP encryption

### ISSUE THREAD

**Issue by flexd** [znuny/Znuny4OTRS-GIArticleSend#2]
Hi!

Normally you can send emails PGP encrypted via OTRS, but I see that your package does not support that yet. In OTRS, `ArticleSend` does support this, via. the `EmailSecurity` field in the options.

```
EmailSecurity => {
            Backend     => 'PGP',                       # PGP or SMIME
            Method      => 'Detached',                  # Optional Detached or Inline (defaults to Detached)
            SignKey     => '81877F5E',                  # Optional
            EncryptKeys => [ '81877F5E', '3b630c80' ],  # Optional
        }
```

If it would be possible to specify this EmailSecurity option into GIArticleSend, that would be great.

Additionally, it would also be great if I could specify a plaintext of the article (that goes into the database), and a ciphertext (pre-encrypted PGP data) that would be sent in the email.

That would allow us to sometimes pre-encrypt something, without having to involve OTRS. This could be practical in some scenarios.

Thanks!

**Comment by rkaldung** [comment]
Available since package version 5.0.4
