### ISSUE TITLE
Update to latest OTRS Patchlevel

### ISSUE THREAD

**Issue by hanneshal** [znuny/Znuny4OTRS-GIArticleSend#6]
There was a minor change in this commit:
https://github.com/OTRS/otrs/commit/ac9063f9e29ae799b6d3de6a062252b5165564a9#diff-e36c34534d0d7f0b8fc95df09fc1cb9a

Which we should use to, so there is no different behaviour in the handling of the encoding

**Comment by jepf** [comment]
Done.
https://github.com/znuny/Znuny4OTRS-GIArticleSend/commit/3d76eb3f8a228464dddabff45f5f962bc91f9d7f
https://github.com/znuny/Znuny4OTRS-GIArticleSend/commit/4a998dc63cb038b4e5b158006146181a6d4c40b9
