### ISSUE TITLE
Signature outgoing email

### ISSUE THREAD

**Issue by rafaadrover** [znuny/Znuny4OTRS-GIArticleSend#7]
When a ticket is created in otrs, it is sent with the signature that has the queue established
When a ticket is created via rest in the same queue, it is send without signature

----
### Expected behavior
When creating a ticket via rest api in a queue that has a signature assigned, the message should be sent with that signature.

### Actual behavior
Currently a ticket is created via rest api in a queue that has a signature assigned, it is sent without the signature

### How to reproduce
Create a queue.
Assign to this queue a signature.
Create a ticket via otrs rest, this ticket will be sent without signature.

**Comment by jepf** [comment]
Thanks for reporting this issue. We will try to reproduce this behavior and fix it.

**Comment by dennykorsukewitz** [comment]
Hi @rafaadrover could you please use our template. We need some information to reproduce this behavior. I have already added the template in your message.

Thank you 👍 🚀

**Comment by rafaadrover** [comment]
> Hi @rafaadrover could you please use our template. We need some information to reproduce this behavior. I have already added the template in your message.
> 
> Thank you 👍 🚀

Hi, @dennykorsukewitz  i have updated de template. 

Regards.

**Comment by dennykorsukewitz** [comment]
Fixed with https://github.com/znuny/Znuny4OTRS-GIArticleSend/commit/e629b4a76e8332de2c99ae32617ec47183e07f9b in Znuny4OTRS-GIArticleSend 6.0.8
