### ISSUE TITLE
Feature request: Multiple recipients

### ISSUE THREAD

**Issue by antigravity8** [znuny/Znuny4OTRS-GIArticleSend#8]
Hey guys,

first I want to thank you for your nice work.

In our company we need to send Articles/Tickets via GI automatically by a script which runs monthly.
Sadly it is only possible to add one 'To' parameter with the ArticleSend feature. So my question is:

Is it possible to add more than one recipient?
That would be really awesome.

We are running OTRS 5 on our Ubuntu-Server.
Just let me know if you need any further information.

Thanks a lot.

Greetings,
Oliver

**Comment by rkaldung** [comment]
Hi, 

Did you tried to recipients, separated with a `,`?

**Comment by antigravity8** [comment]
> Hi,
> 
> Did you tried to recipients, separated with a `,`?

Yes I did -> syntax-error :(
Even with ['first@mail.tld', 'second@mail.tld']


With two (or more) 'To'-Parameters the second one overwrites the first one.

**Comment by dennykorsukewitz** [comment]
Hi @antigravity8 can you please send us your request?
I think we just have a slight syntax error here.

**Comment by antigravity8** [comment]
The request comes out of a ruby script I've created:

  request.body = JSON.dump({
    "Ticket" => {
      "Title" => "#{title}",
      "Type" => "ServiceRequest",
      "Queue" => "#{queue}",
      "State" => "open",
      "Priority" => "3 normal",
      "CustomerUser" => "#{cust_user}"
    },
    "Article" => {
      "ArticleType" => "email-external",
      "SenderType" => "agent",
      "ArticleSend" => "1",
      "To" => "#{cust_user}", "mymail@adress.tld",
      "Subject" => "#{subject}",
      "Body" => "#{article_result}",
      "ContentType" => "text/plain; charset=utf8",
      "NoAgentNotify" => "0",
      "IsVisibleForCustomer" => "1"
    },
    "Attachment" => "#{attachment_body}"

If I start the script with this 'body' I get:
syntax error, unexpected ',', expecting =>

Without the comma seperated list (only To cust_user) it works.

**Comment by dennykorsukewitz** [comment]
Hi @antigravity8 thanks for the request.

You have a syntax error in "To" line. `"#{cust_user}, mymail@adress.tld",`


```
"ArticleSend" => "1",
"To" => "#{cust_user}, mymail@adress.tld",
"Subject" => "#{subject}",
```

This should solve your problem.

**Comment by antigravity8** [comment]
Thanks... it works!
